### ISSUE TITLE
Improve consistency across different languages

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#13]
**Problem:** _When the problems first get created, someone creates a test suite in one language with a few inputs and outputs, and this gets ported to other languages. Once the problem is in production, various people find interesting edge cases, and this usually gets fixed in one language but not the others._

**Solution:** _Create a shared JSON document that encodes a standardized set of inputs/outputs for each problem. This shared JSON can then be used to generate a test suite in various languages. The generated test suite gets committed to the repo, and we can generate regularly (or whenever the shared metadata changes)._

**Example**
- Shared inputs/outputs: https://github.com/exercism/x-common/blob/master/hamming.json
- Generated test suite: https://github.com/exercism/xruby/blob/master/hamming/hamming_test.rb
- Generator: https://github.com/exercism/xruby/blob/master/bin/generate-hamming

**TODO**: There's one issue per exercise that is still missing a JSON document with shared data https://github.com/exercism/todo/labels/shared-test-data (also listed below as references).

See also: #8

**Comment by aarti** [comment]
HackerRank does something similar with inputs and outputs which I find it confusing sometimes, may because they don't share the test data. It's nice to see the tests and the test data side by side when you are learning.

**Comment by kytrinyx** [comment]
Yes, the shared test data wouldn't be used to create cryptic tests, but rather to generate the test suites that we currently use.

Here's an example: https://github.com/exercism/xruby/blob/master/hamming/hamming_test.rb

That's the generated test suite, and the generator that creates it is here: https://github.com/exercism/xruby/blob/master/bin/generate-hamming -- it uses some shared code that all the generators can use, and some custom code just for that exercise.

**Comment by wobh** [comment]
Why abbreviate "message" to "msg"?

**Comment by kytrinyx** [comment]
Probably because this used the Go tests originally, and go has a thing for abbreviations. I'll fix the Go and Ruby generators if we change that.

**Comment by petertseng** [comment]
I've given a little bit of thought to this recently since I added test data for largest-series-product. Would like to talk about a bit.

I can personally add test generators to at least Go and Ruby, but I can make no guarantees for any other languages. Perhaps it is prudent for me to file issues on the other language tracks so they know. That leads me to ask a few questions.

(I use "student" below for "someone who completes an exercise" rather than "user" because I couldn't think of a good word for that, but I'll take suggestions)

* Are there other problems that have gotten shared test data, but tracks are not using them? How should we track progress for that?
* In general, if someone contributes shared test data for a given problem, how do we notify track maintainers of the tracks with that problem? Should the contributor file issues? Someone else?
* You may recall that I had specific opinions on how some language tracks are doing their test suites for largest-series-product. In particular, I opined that some test suites too severely funneled students toward a particular implementation whereas there are at least two implementations to choose between. They test internal implementation details (some helper functions) instead of the actual problem (Finding the largest series product!). This means that for my Haskell and Clojure submissions for that problem I was "forced" to write a helper function that my actual submission doesn't use to find the largest product. Two sub-points for this:
  * I wonder if there is a way for all track maintainers to see notes on a problem so they don't inadvertently write test suites that are restrictive in this fashion.
  * Playing devil's advocate against myself, there is a distinct *advantage* of writing test suites that guide students toward a solution: They give students hints on a potentially hard problem. This is actually a fine thing to do! But I wish there were a way of giving hints that didn't restrict students like this. Maybe I suggest how Elixir did it here? https://github.com/exercism/xelixir/tree/master/zipper/hints
  * Yet another *advantage* of writing test suites in this way: It's a good thing to get students in the habit of testing helper functions so that they can build larger solutions from smaller parts that they know to be working. But I'm going to argue here that this should be up to the student to do this! Any way to guide them in that direction? Unlike my previous point, I have not thought of a suggestion for this yet!

By the way, just as how we have track maintainers who are interested in all problems in a given *track*, I'm going to say that I am very interested in this particular *exercise* of largest-series-product, across various tracks. I don't think any separate group needs to be made to mark that (unlike track maintainers who can write to their associated track repository), since being interested in an exercise mostly consists of talking to the various track maintainers, and this is a short-term thing rather than the long-term track maintainership. I'm just bringing this up because I imagine this pattern may emerge organically for various other exercises as well with people volunteering for them.

**Comment by kytrinyx** [comment]
We can check which language tracks include a given exercise at the x-api endpoint `/problems/:slug`: http://x.exercism.io/problems/largest-series-product

We can also check whether a json file exists by checking `https://github.com/exercism/x-common/blob/master/:slug.json`

I don't know how to check for generators, though, unless we create a convention. Maybe each generator should have a `./bin/generate-:slug.sh` script, even if all that script does is to call the real generator for that language/problem.

I've got small scripts locally to publish issues to all the tracks (or a set of tracks), so this could be expanded upon using all the above data.

I would absolutely prefer if test suites didn't guide people too hard towards a given solution... but I know that for some students who are code newbies it can be really hard to complete an exercise without some extra hand-holding. Perhaps we can always try to avoid the funneling towards a given solution, and then put harder exercises farther back in the track so that by the time people get to it, they've built up some skills/confidence.

**Comment by petertseng** [comment]
> I don't know how to check for generators, though, unless we create a convention.

I imagine a convention will be beneficial to keep track maintainers sane as well! Taking a look at the current state of the world in the go repo at least, though, we just have a https://github.com/exercism/xgo/blob/master/gen/gen.go that seems to work for *any* exercise with a .json file. I have various thoughts about that:

* So if we adopt this convention, all of the go track's generators will be trivial. Will this cause fatigue from having to write trivial generator scripts?
* Should instead we check for the presence of generated test data? That seems difficult, since the generated data may show up in different form per language.
* We could punt on detecting generators and/or test data, and just file issues on all language tracks with that problem, which can trivially be closed if the language track already has the test data. Again, potential for fatigue from the extra issue volume.
* Let's even imagine a perfect world where we have the ability to check for the presence of a generator and every track is following convention in that regard. Now, I *update the existing test data* for a given problem. How do we check that all tracks with that problem have updated their data accordingly?

I don't know the answers to these questions yet, so mostly thinking out loud right now.

**Comment by kytrinyx** [comment]
> Will this cause fatigue from having to write trivial generator scripts?

If they're that trivial, then I'm sure we can script their creation. I don't think it's a problem.

> Should instead we check for the presence of generated test data?

As you noted, this seems fraught with complexity.

> We could punt on detecting generators and/or test data, and just file issues on all language tracks with that problem, which can trivially be closed if the language track already has the test data.

Oh, right. I actually really like this idea. It seems more satisfying to close an issue that turned out to be unnecessary than to create a file that's just there so we don't have to create that issue.

> Now, I update the existing test data

Haha, oh, man. I have no idea! How about part of updating the test data is to run a script (that we will commit to the x-common repository) that will add an issue to each language that implements the problem and say "if you have a generator, time to rerun the script. If not, check out this new data--you might be interested in manually updating the test suite with new edge cases".

**Comment by petertseng** [comment]
> How about part of updating the test data is to run a script... that will add an issue to each language that implements the problem

I think I'm on board with that. And it seems that that will be the same script (or at least very similar) as the one that will be used for the initial run too, so less extra work there.

I think we are reaching agreement on the general approach for this. Given that, to my specific question of "should I personally file issues on every language track of largest-series-product", I guess that means I'll wait until that script is done, at which point you could file it. (Or I can too, good to test with many users)

**Comment by kytrinyx** [comment]
> I think we are reaching agreement on the general approach for this.

Yes, this sounds both reasonable and doable.

I'll write a first draft of the script and then we can both test it.

**Comment by petertseng** [comment]
A small note as I go to write the xgo generator for LSP... I may have been hilariously wrong about

> we just have a https://github.com/exercism/xgo/blob/master/gen/gen.go that purports to work for any exercise with a .json file

That's just a package used by individual generators. So my concern about fatigue from writing trivial scripts was actually incorrect (in that the scripts would not be trivial, not that the scripts would be unnecessary).

Nevertheless, I say it's still OK to just file the issues anyway... simply because even if a track already has a generator, its data might be out of date if the test data has been edited since then.

I may submit a few PRs to various tracks to get the new test data so that they can start using those in the meantime, if they don't have time to write a generator yet. I guess the importance of that might depend on how many submissions will get submitted with the old test data. largest-series-product is probably placed late in many tracks so it probably doesn't get much traffic. So not the highest priority. But will do if I have extra time.

**Comment by kytrinyx** [comment]
Yepp, that sounds great. I looked at what is necessary to write the script for submitting issues and it's going to be pretty straight forward. I've put it on my todo list for "soonish".

**Comment by kytrinyx** [comment]
OK, I've created a simple tool at github.com/exercism/blazon (uploading a release right now, but since you have go you can just go get it) - Call it without arguments to get the flags.

**Comment by petertseng** [comment]
Can you double check on whether that repo is visible? I am getting a 404 on that

**Comment by kytrinyx** [comment]
Oops. I created it under my personal account, not the exercism org. I've moved it now.

**Comment by NobbZ** [comment]
Inspired by a discussion in exercism/xelixir#291, I wanted to do some analyze of the current testdata for `diamond` across tracks, so I looked here for the ticket that tells me which tracks do implement it. But it seems as if it is missing in the list. Could you open up a ticket for it @kytrinyx?

**Comment by kytrinyx** [comment]
@NobbZ I'm going to go ahead and recreate the correct issues over in x-common. In the meanwhile, here you go: http://exercism.io/contribute/canonical-data/diamond

**Comment by kytrinyx** [comment]
Find up to date issue here: https://github.com/exercism/x-common/issues/552
