### ISSUE TITLE
Extract shared inputs/outputs for exercise Strain

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#152]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `strain.json` containing the inputs and expected outputs for Strain.

Strain has been implemented in the following languages:
- https://github.com/exercism/xcsharp/tree/master/strain
- https://github.com/exercism/xerlang/tree/master/strain
- https://github.com/exercism/xfsharp/tree/master/strain
- https://github.com/exercism/xgo/tree/master/strain
- https://github.com/exercism/xhaskell/tree/master/strain
- https://github.com/exercism/xjava/tree/master/strain
- https://github.com/exercism/xjavascript/tree/master/strain
- https://github.com/exercism/xlfe/tree/master/strain
- https://github.com/exercism/xlisp/tree/master/strain
- https://github.com/exercism/xperl5/tree/master/strain
- https://github.com/exercism/xruby/tree/master/strain
- https://github.com/exercism/xswift/tree/master/strain

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I took a brief look at this one and the related [List Ops]( (https://github.com/exercism/todo/issues/109) data story.  I wonder if anyone has proposed or talked about how to represent a function in the canonical-json.data because these problems expect (as an input to the methods under test) some kind of lambda/proc/function/predicate. 

I might be able to proceed here if someone could suggest a guideline on how we might try to represent a function.  

Here is a handful of examples of the solution (`example`) code from `x-common`:
https://github.com/exercism/xgo/blob/master/exercises/strain/example.go
https://github.com/exercism/xjava/blob/master/exercises/strain/src/example/java/Strain.java
https://github.com/exercism/xjavascript/blob/master/exercises/strain/example.js
https://github.com/exercism/xperl5/blob/master/exercises/strain/Example.pm
https://github.com/exercism/xruby/blob/master/exercises/strain/example.rb

Given we're using JSON, I wonder if using Javascript function notation would be appropriate?

**Comment by petertseng** [comment]
Good question - we also ran into this when looking at Accumulate in #64 - at the time we just decided to close it, but if we come up with a good idea for representing functions I would imagine we can do Accumulate too... were it not for the fact that we want to fold Accumulate into list-ops.

Quick check here, do we or do we not want to do the same treatment for Strain (fold into list-ops?)

I will tell you that in React, I also had to deal with representing arbitrary functions. What I decided on was https://github.com/exercism/x-common/blob/master/exercises/react/canonical-data.json#L95

I have not heard word from any track auto-generating tests whether they liked this notation or not. It is possible no track has attempted it yet.

**Comment by bunnymatic** [comment]
I suspect you're asking the larger group but, to me, folding those together
makes sense,

That function representation seems ok.  I can give that a try.  I'll put my
effort into the list-ops data story.

**Comment by bunnymatic** [comment]
It feels like folding strain and accumulate into here should be (pretty much) a no-op since the list ops tests (from my survey of existing language tracks) include both filter and reduce which is basically strain and accumulate.  just my 2c

**Comment by kytrinyx** [comment]
> It feels like folding strain and accumulate into here should be (pretty much) a no-op 

Yeah, I think you're right.

**Comment by kytrinyx** [comment]
Find up to date issue here: https://github.com/exercism/x-common/issues/552
