### ISSUE TITLE
Extract shared inputs/outputs for exercise Bank Account

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#70]
Goal: https://github.com/exercism/todo/issues/13

---

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---

Create a file `bank-account.json` containing the inputs and expected outputs for Bank Account.

Bank Account has been implemented in the following languages:
- https://github.com/exercism/xclojure/tree/master/bank-account
- https://github.com/exercism/xelixir/tree/master/bank-account
- https://github.com/exercism/xerlang/tree/master/bank-account
- https://github.com/exercism/xfsharp/tree/master/bank-account
- https://github.com/exercism/xgo/tree/master/bank-account
- https://github.com/exercism/xhaskell/tree/master/bank-account
- https://github.com/exercism/xlfe/tree/master/bank-account
- https://github.com/exercism/xscala/tree/master/bank-account

See the following files for some examples:
- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by bunnymatic** [comment]
I assume all these todo's for json data files are still valid and need doing?

I'll probably start doing some of this busy work.  If these issues are *not* valid or don't need doing, please let me know so I don't waste a bunch of time on them.

Thanks

**Comment by bunnymatic** [comment]
I believe the description of this ticket should read something more like this:

-------------
Skillset: This is mostly a matter of reading code (test suites) in several languages and creating some JSON.
-------------

Create the three files `canonical-data.json`, `description.md`, `metadata.yml` containing the inputs and expected outputs, description and metadata for the Bank Account problem.

Already Implemented solutions where you should get the canonical data, etc.:
* https://github.com/exercism/xclojure/tree/master/exercises/bank-account
* https://github.com/exercism/xelixir/tree/master/exercises/bank-account
* https://github.com/exercism/xerlang/tree/master/exercises/bank-account
* https://github.com/exercism/xfsharp/tree/master/exercises/bank-account
* https://github.com/exercism/xgo/tree/master/exercises/bank-account
* https://github.com/exercism/xhaskell/tree/master/exercises/bank-account
* https://github.com/exercism/xlfe/tree/master/exercises/bank-account
* https://github.com/exercism/xscala/tree/master/exercises/bank-account

Examples of the common data format used to store exercise descriptions, metadata and canonical test data:
* https://github.com/exercism/x-common/blob/master/exercises/bob
* https://github.com/exercism/x-common/blob/master/exercises/clock
* https://github.com/exercism/x-common/blob/master/exercises/custom-set
* https://github.com/exercism/x-common/blob/master/exercises/gigasecond
* https://github.com/exercism/x-common/blob/master/exercises/hamming
* https://github.com/exercism/x-common/blob/master/exercises/leap

**Comment by petertseng** [comment]
Hello and thank you!

> I assume all these todo's for json data files are still valid and need doing?

I am relatively sure that the issues in this repo *do* still need doing, however their descriptions reference some out of date paths (as you have found out), sorry.

I personally have found these issues a decent starting point (not perfect for the above reason), since they are visible on Github in a way I can link to. Also makes it possible to keep track of whether someone is working on each problem.

The primary source of truth for which problems still need doing should be whether the `exercises/$SLUG/canonical-data.json` is present in the x-common repo.

It is possible to get a JSON list from http://x.exercism.io/v3/problems/data-todos - I like to use the https://stedolan.github.io/jq/ to get a list of just the problems that need JSON files:

    curl http://x.exercism.io/v3/problems/data-todos | jq '.[] | map(.["slug"])'

I will do a quick pass to make sure that each open issue in this repo still does indicate a problem that needs a JSON file, though we will need some good way of mass updating all the descriptions.

> I believe the description of this ticket should read something more like this:

Indeed, our directory structures have changed in the year+ since these were filed. Sorry for the mess. I like to programmatically acquire the list of all implementing tracks like this:

    curl http://x.exercism.io/v3/problems/data-todos | jq '.[] | map(select(.["slug"] == "accumulate"))'

(replacing `accumulate` with whichever problem I am working on at the time)

**Comment by petertseng** [comment]
>  programmatically acquire the list of all implementing tracks like this:

editing to clarify: this also points to the /exercises/ directory within each track.

**Comment by bunnymatic** [comment]
sounds good.  Thanks for the update

I'll get to work on this one.

**Comment by bunnymatic** [comment]
For the test data sets, should I shoot for lowest common denominator or the most well tested exercise?

It seems (for the bank account) at a quick glance of the first 4 languages, the Erlang test suite may have a few extra test cases.  I'm wondering if that should be the model?  or should i do something more like a sample set that matches the common union of the different language tests.

**Comment by petertseng** [comment]
The general advice we have at https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data is generally "All tests should be essential to the problem. Ensure people can get the first test passing easily. Then each following test should ideally add a little functionality. People should be able to solve the problem a little at a time. Avoid test cases that don't introduce any new aspect and would already pass anyway."

If you are unsure, what you could do is include all of them, and note in the commit message which cases were common to all tracks versus which cases were only in a few. Or the opposite, include just the intersection, but still note in the commit messages which extras were only in some tracks. Track maintainers can discuss on the PR what seems like a good set of tests for all tracks.

---

Also, since you chose bank-account as the first one you're doing, I have some specific thoughts about this problem.

Most problems you will see are stateless - write a function, give it some inputs, expect a certain output. All exercises listed in the example section in fact follow that pattern (custom-set is a bit more complex, but fundamentally it still fits into that pattern, just with multiple functoins)

You may find that bank-account doesn't fall into that pattern if it is very stateful - create a bank account, do some things to that bank account, check some state of that bank account.

If it looks like the bank-account tests can't fit well with the examples listed, try looking at what happened in https://github.com/exercism/x-common/pull/488 and https://github.com/exercism/x-common/pull/358 , which were also two very stateful exercises.

(Of course, if you find that bank-account can fit well into the stateless model, then you can ignore everything I've said, no worries!)

**Comment by bunnymatic** [comment]
Thanks.  that's great info.  I chose bank-account arbitrarily.  maybe i'll
start on a simpler one first.

**Comment by bunnymatic** [comment]
I will *not* be working on this ticket but will pick up one of the stateless (simpler) shared-test-data stories first.  Just FYI

**Comment by kytrinyx** [comment]
I created a (bare bones) page for the canonical data that still needs to be extracted:

http://exercism.io/contribute/canonical-data

The sidebar contains all of the problems that don't have a canonical-data.json file.

I've been wondering if it's time to retire the _todo_ repo (since it's so far out of context from the rest of the project), and generate fresh issues in github.com/exercism/x-common for the missing canonical data.

We could link to the page that contains the up-to-date list of implementations from the issue.

**Comment by kytrinyx** [comment]
Find up to date issue here: https://github.com/exercism/x-common/issues/552

(@petertseng, would you add your thoughts about this exercise to the new issue?)
