### ISSUE TITLE
Extract shared inputs/outputs for exercise Bob

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#75]
Goal: https://github.com/exercism/todo/issues/13

--------------

**Skillset:** This is mostly a matter of reading code (test suites) in several languages and creating some JSON.

---------------

Create a file `bob.json` containing the inputs and expected outputs for Bob.

Bob has been implemented in the following languages:

- https://github.com/exercism/xclojure/tree/master/bob
- https://github.com/exercism/xcoffeescript/tree/master/bob
- https://github.com/exercism/xcpp/tree/master/bob
- https://github.com/exercism/xcsharp/tree/master/bob
- https://github.com/exercism/xecmascript/tree/master/bob
- https://github.com/exercism/xelisp/tree/master/bob
- https://github.com/exercism/xelixir/tree/master/bob
- https://github.com/exercism/xerlang/tree/master/bob
- https://github.com/exercism/xfsharp/tree/master/bob
- https://github.com/exercism/xgo/tree/master/bob
- https://github.com/exercism/xhaskell/tree/master/bob
- https://github.com/exercism/xjava/tree/master/bob
- https://github.com/exercism/xjavascript/tree/master/bob
- https://github.com/exercism/xlfe/tree/master/bob
- https://github.com/exercism/xlisp/tree/master/bob
- https://github.com/exercism/xlua/tree/master/bob
- https://github.com/exercism/xobjective-c/tree/master/bob
- https://github.com/exercism/xocaml/tree/master/bob
- https://github.com/exercism/xperl5/tree/master/bob
- https://github.com/exercism/xpython/tree/master/bob
- https://github.com/exercism/xruby/tree/master/bob
- https://github.com/exercism/xrust/tree/master/bob
- https://github.com/exercism/xscala/tree/master/bob
- https://github.com/exercism/xscheme/tree/master/bob
- https://github.com/exercism/xswift/tree/master/bob

See the following files for some examples:

- https://github.com/exercism/x-common/blob/master/bob.json
- https://github.com/exercism/x-common/blob/master/clock.json
- https://github.com/exercism/x-common/blob/master/custom-set.json
- https://github.com/exercism/x-common/blob/master/gigasecond.json
- https://github.com/exercism/x-common/blob/master/hamming.json
- https://github.com/exercism/x-common/blob/master/leap.json

**Comment by masters3d** [comment]
Are these considered to be done since they seem to already have data?

https://github.com/exercism/todo/issues/75	https://github.com/exercism/x-common/blob/master/bob.json
https://github.com/exercism/todo/issues/80	https://github.com/exercism/x-common/blob/master/clock.json
https://github.com/exercism/todo/issues/84	https://github.com/exercism/x-common/blob/master/custom-set.json
https://github.com/exercism/todo/issues/93	https://github.com/exercism/x-common/blob/master/gigasecond.json
https://github.com/exercism/todo/issues/98	https://github.com/exercism/x-common/blob/master/hamming.json
https://github.com/exercism/todo/issues/100	https://github.com/exercism/x-common/blob/master/hello-world.json
https://github.com/exercism/todo/issues/105	https://github.com/exercism/x-common/blob/master/leap.json
https://github.com/exercism/todo/issues/112	https://github.com/exercism/x-common/blob/master/meetup.json
https://github.com/exercism/todo/issues/134	https://github.com/exercism/x-common/blob/master/raindrops.json
https://github.com/exercism/todo/issues/137	https://github.com/exercism/x-common/blob/master/rna-transcription.json
https://github.com/exercism/todo/issues/140	https://github.com/exercism/x-common/blob/master/roman-numerals.json
https://github.com/exercism/todo/issues/161	https://github.com/exercism/x-common/blob/master/word-count.json

**Comment by kytrinyx** [comment]
Yeah. Dang it--I did the check wrong in the script to see which ones had them! Thanks :)
